# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-06 05:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=50)),
                ('imdb_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10.0), django.core.validators.MinValueValidator(1.0)])),
                ('popularity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)])),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set([('name', 'director')]),
        ),
    ]
